### ISSUE TITLE
missing project architecture presentation

### ISSUE THREAD

**Issue by Eothred** [openxal/openxal.github.io#2]
I noticed that the (in my opinion) very useful presentation by Tom on the project layout found on [SourceForge](https://sourceforge.net/projects/xaldev/files/Architecture/) does not seem to be copied to GitHub. I might just have missed where it is. If it is not on github, perhaps it could be convenient to have it linked on this page?

The same might be true for other documents on the [files](https://sourceforge.net/projects/xaldev/files/) page on sourceforge.

**Comment by tapsns** [comment]
Thanks for finding this. I forgot to copy the SourceForge files over. I think all these files (if still relevant) should be migrated to md format. That will allow them to be maintained as living documents with GitHub tracking of edits.

**Comment by Eothred** [comment]
Ah, that sounds like a very good plan to convert to markdown. However, is that easy to do for slides as this specific document is?

**Comment by tapsns** [comment]
Sorry! Probably not for that one. Those presentations will be copied over directly. I was thinking about the other documents (non-presentation) which describe our project such as versioning guidelines and software management guide, etc. Those documents are living documents and would best be converted to markup.

I’ve got a few priority tasks to complete here at SNS before I have time to cycle back to Open XAL. I expect (hopefully) to get to it this week.

On Feb 22, 2016, at 1:01 PM, Yngve Inntjore Levinsen <notifications@github.com<mailto:notifications@github.com>> wrote:

Ah, that sounds like a very good plan to convert to markdown. However, is that easy to do for slides as this specific document is?

**Comment by tapsns** [comment]
Okay, I've copied the documents over to our website on GitHub.

**Comment by Eothred** [comment]
Thanks!
